# Generated by Django 3.2.7 on 2021-09-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(upload_to='images/profiles'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/meals'),
        ),
    ]
