# Generated by Django 3.2.7 on 2021-09-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20210922_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
