# Generated by Django 3.2.7 on 2021-09-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Preparing', 'Preparing'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
