# Generated by Django 3.2.7 on 2021-09-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20210923_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Preparing', 'Preparing'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Ordered', max_length=50),
        ),
    ]
