# Generated by Django 3.2.7 on 2021-09-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Preparing', 'Preparing'), ('InProgress', 'InProgress'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Ordered', max_length=50),
        ),
    ]
