# Generated by Django 3.2.7 on 2021-09-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivary_date',
            field=models.DateField(auto_now=True),
        ),
    ]
