# Generated by Django 3.2.7 on 2021-09-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_order_delivary_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivary_date',
        ),
    ]
