# Generated by Django 3.2.7 on 2021-10-02 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ceated',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.invoice')),
            ],
        ),
    ]
