# Generated by Django 3.2.7 on 2021-10-05 06:55

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_auto_20211002_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='price',
            field=computed_property.fields.ComputedFloatField(compute_from='get_items_price', default=1, editable=False),
            preserve_default=False,
        ),
    ]
