# Generated by Django 3.2.7 on 2021-10-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_invoice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
