# Generated by Django 3.2.7 on 2021-10-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_auto_20211005_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
