# Generated by Django 3.2.7 on 2021-10-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0025_auto_20211007_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('InProgress', 'InProgress'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=50),
        ),
    ]
